language: go

go:
  - 1.13.x
  - 1.14.x

addons:
  apt:
    packages:
      - rpm
      - ruby-full

env:
  - GO111MODULE=on

script:
  - curl -Ls https://git.io/ttask.sh | sh
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
  - gem install bundler
  - bundle update --bundler
  - bundler install
  - ./bin/task ci
