version: '2'
output: 'prefixed'

includes:
  _: https://raw.githubusercontent.com/FasterArbeit/task/master/go.yml

vars:
  BINARY_NAME: 'blogctl'
  REPOSITORY_NAME: 'blogctl'
  PATH: 'github.com/RaphaelPour/blogctl'

tasks:
  bin:
    desc: Build the go binary
    cmds:
      - go build -a -ldflags "-X {{.PATH}}/cmd.BuildDate={{.DATE}} -X {{.PATH}}/cmd.BuildVersion={{.VERSION}} -extldflags '-static' -s -w" -o ci-build/{{.BINARY_NAME}}
    vars:
      DATE:
        sh: date '+%Y-%m-%dT%H:%M:%S%z'
      VERSION:
        sh: git describe --tags || git describe --always
  bin-cov:
    desc: Build coverage binary for integration tests
    cmds:
      - mkdir -p ci-build
      - go test -covermode=atomic -coverpkg="./..." -c -tags main  -o ci-build/{{.BINARY_NAME}}.test
  test:
    desc: Run go test unittests
    cmds:
      - mkdir -p coverage
      - go test -run "^Test[^_]" -v ./... -coverprofile=coverage/unittest_coverage.out -covermode=atomic
  integration-test:
    desc: Run integration tests
    cmds:
      - mkdir -p coverage
      - bundler exec rspec spec.rb
  
  coverage:
    desc: Generate coverage report
    cmds:
      - |
        echo "mode: atomic" > coverage/total
        grep "^github.com" -h coverage/*.out | sort >> coverage/total
        go tool cover -html=coverage/total -o coverage/coverage.html
  ci:
    desc: Run ci tasks
    cmds:
      - task: lint
      - task: bin-cov
      - task: test
      - task: integration-test
      - task: coverage

