name: release

on:
  push:
    tags:
      - '*'
    
jobs:
  build:
    name: Relase blogctl
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: install task
        run: curl -Ls https://git.io/ttask.sh | sh
      - run: ./bin/task bin
      - run: mv ci-build/blogctl ci-build/blogctl_${{ matrix.goos }}_${{ matrix.goarch }}
      - uses: actions/upload-artifact@master
        with:
          name: build-artifacts
          path: ci-build
  release:
    name: Relase blogctl
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: install changelogger
        run: curl -Ls https://git.io/changelogger.sh | sh
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build-artifacts
          path: ci-build
      - name: Save changelog entries of current release
        run: ./bin/changelogger release last > CHANGELOG_RELEASE.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG_RELEASE.md
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
